---
- name: Windows PowerShell Playbook
  hosts: window2
  tasks:
    - name: Execute PowerShell Script
      script: ~\Scripts\process.ps1 universe
      register: ipconfig
    - debug: var=ipconfig

