  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define la421 Switch Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: la421 Switch Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/la421/files/la421.cfg"