---
# tasks file for ETSOAK LP14 Switch
- name: Obtain Login
  include_vars: pass.yaml

- name: Define ETSOAK LP14 Switch Provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

- include: etsoak-lp14-sg300-config.yaml
