---
# tasks file for ETSOAK LP24 Switch
- name: Obtain Login
  include_vars: pass.yaml

- name: Define ETSOAK LP24 Switch Provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

- include: etsoak-lp24-sg300-config.yaml
