  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ETSOAK Router Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ETSOAK Router Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/etsoak-rt1/files/etsoak-rt1.cfg"