---
# tasks file for ETS SPF Switch2
- name: Obtain Login
  include_vars: pass.yaml

- name: Define ETSOAK SPF Switch2 Provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

- include: spf-sw2-config.yaml
