  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ETSOAK SPF Switch2 Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ETSOAK SPF Switch2 Config
    ios_config:
      timeout: 60
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/spf-sw2/files/spf-sw2.cfg"