  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ETS Admin Router Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ETS Admin Router Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/ets-rt1/files/ets-rt1.cfg"