  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ETS LP15 Switch Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: TT ETS LP15 Switch Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/ets-lp15-sg300/files/ets-lp15-sg300.cfg"