  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define ETS LA521 Switch Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: ETS LA521 Switch Config
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      src: "~/ETS-Demo/roles/la521/files/la521.cfg"