---
# tasks file for ETS LA521 Switch
- name: Obtain Login
  include_vars: pass.yaml

- name: Define ETS LA521 Provider
  set_fact:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

- include: la521-config.yaml
